blank_issues_enabled: false
contact_links:
  - name: Start a Discussion
    url: https://github.com/ngoc-quoc-huynh/nfc_manager/discussions/
    about: We encourage you to start a discussion for any questions, suggestions, or feedback regarding the plugin.
