name: nfc_manager_platform_interface_example
description: Demonstrates how to use the nfc_manager_platform_interface plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  nfc_manager_platform_interface:
    # When depending on this package from a real application you should use:
    #   nfc_manager_platform_interface: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  cosee_lints: ^0.6.0
  dart_code_linter: ^1.2.1
