name: nfc_manager
description: A Flutter plugin for managing NFC (Near Field Communication) interactions.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  nfc_manager_platform_interface:
    path: ../nfc_manager_platform_interface
  nfc_manager_android:
    path: ../nfc_manager_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test_cov_console: ^0.2.2

  # Linter
  cosee_lints: ^0.10.1
  dart_code_linter: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: nfc_manager_android
