name: nfc_manager_android_example
description: Demonstrates how to use the nfc_manager_android plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  nfc_manager_android:
    # When depending on this package from a real application you should use:
    #   nfc_manager_android: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  cosee_lints: ^0.10.1
  dart_code_linter: ^3.0.0

flutter:
  uses-material-design: true
