name: nfc_manager_example
description: Demonstrates how to use the nfc_manager plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  nfc_manager:
    # When depending on this package from a real application you should use:
    #   nfc_manager: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  # Linter
  cosee_lints: ^0.6.0
  dart_code_linter: ^1.2.1

flutter:
  uses-material-design: true
