name: nfc_manager

on:
  push:
    paths:
      - 'nfc_manager/**'
      - '.github/workflows/nfc_manager.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./nfc_manager

    steps:
      - uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v3
        with:
          install_args: "flutter"
          cache: true

      - name: Cache flutter dependencies
        uses: actions/cache@v6
        with:
          path:  ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('./nfc_manager/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-
      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run code metrics
        run: dart run dart_code_linter:metrics analyze . --set-exit-on-violation-level=warning
      - name: Run tests
        run: |
          flutter test --coverage --test-randomize-ordering-seed=random
          dart run test_cov_console
