name: nfc_manager_android

on:
  push:
    paths:
      - 'nfc_manager_android/**'
      - '.github/workflows/nfc_manager_android.yaml'

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./nfc_manager_android

    steps:
      - uses: actions/checkout@v4

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v4
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf/installs
            ~/.asdf/plugins
            ~/.asdf/shims
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
      - name: Install asdf
        uses: asdf-vm/actions/install@v4
        # See https://github.com/asdf-vm/actions/issues/445
        if: steps.cache-asdf.outputs.cache-hit != 'true'
      - name: Reshim asdf
        run: asdf reshim

      - name: Cache flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ./nfc_manager_android/.dart_tool
            ./nfc_manager_android/example/.dart_tool
          key: ${{ runner.os }}-flutter-android-${{ hashFiles('./nfc_manager_android/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-android-
      - name: Install dependencies
        run: flutter pub get

      - name: Create local.properties
        working-directory: ./nfc_manager_android/example/android
        run: |
          FLUTTER_PATH=$(asdf where flutter)
          echo "flutter.sdk=$FLUTTER_PATH" > ./local.properties
      - name: Run android tests
        working-directory: ./nfc_manager_android/example/android
        run: ./gradlew testDebugUnitTest --no-daemon

      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run code metrics
        run: dart run dart_code_linter:metrics analyze . --set-exit-on-violation-level=warning
      - name: Run tests
        run: |
          flutter test --coverage --test-randomize-ordering-seed=random
          dart run test_cov_console
